spring.application.name=spingBootAIApplication
server.port=9090
# Hugging Face API
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.api.key=
huggingface.model.id=meta-llama/Meta-Llama-3-8B-Instruct